"""initial schema

Revision ID: 3ba965fb2922
Revises:
Create Date: 2026-09-28 02:26:56.024636
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '3ba965fb2922'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_categories',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('parent_id', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('institute_id', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('countries',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('company_id', sa.String(length=80), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('category_id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('duration_max', sa.Integer(), nullable=True),
    sa.Column('price_member', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_passage', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('requires_machine', sa.Boolean(), nullable=False),
    sa.Column('requires_appointment', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['service_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_category_id'), 'services', ['category_id'], unique=False)
    op.create_table('regions',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('country_id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('institutes',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('region_id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('institute_id', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.String(length=80), nullable=True),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['institute_id'], ['institutes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_institute_id'), 'employees', ['institute_id'], unique=False)
    op.create_table('queue_tickets',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('institute_id', sa.String(length=80), nullable=False),
    sa.Column('ticket_number', sa.String(length=40), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=True),
    sa.Column('customer_id', sa.String(length=80), nullable=True),
    sa.Column('subscription_id', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('arrival_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estimated_start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_employee_id', sa.String(length=80), nullable=True),
    sa.Column('created_by_id', sa.String(length=80), nullable=True),
    sa.Column('checkout_employee_id', sa.String(length=80), nullable=True),
    sa.Column('checkout_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_employee_id', sa.String(length=80), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_method', sa.String(length=40), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['institute_id'], ['institutes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institute_id', 'idempotency_key', name='uq_queue_ticket_institute_idempotency')
    )
    op.create_index(op.f('ix_queue_tickets_idempotency_key'), 'queue_tickets', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_queue_tickets_institute_id'), 'queue_tickets', ['institute_id'], unique=False)
    op.create_index(op.f('ix_queue_tickets_status'), 'queue_tickets', ['status'], unique=False)
    op.create_index(op.f('ix_queue_tickets_ticket_number'), 'queue_tickets', ['ticket_number'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('institute_id', sa.String(length=80), nullable=False),
    sa.Column('service_id', sa.String(length=80), nullable=False),
    sa.Column('employee_id', sa.String(length=80), nullable=False),
    sa.Column('customer_name', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['institute_id'], ['institutes.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_employee_id'), 'appointments', ['employee_id'], unique=False)
    op.create_index(op.f('ix_appointments_end_time'), 'appointments', ['end_time'], unique=False)
    op.create_index(op.f('ix_appointments_institute_id'), 'appointments', ['institute_id'], unique=False)
    op.create_index(op.f('ix_appointments_service_id'), 'appointments', ['service_id'], unique=False)
    op.create_index(op.f('ix_appointments_start_time'), 'appointments', ['start_time'], unique=False)
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    op.create_table('ticket_lines',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('ticket_id', sa.String(length=80), nullable=False),
    sa.Column('service_id', sa.String(length=80), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('revenue_category', sa.String(length=40), nullable=False),
    sa.Column('performed_by_employee_id', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['queue_tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_lines_ticket_id'), 'ticket_lines', ['ticket_id'], unique=False)
    op.create_table('service_sessions',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('ticket_line_id', sa.String(length=80), nullable=True),
    sa.Column('institute_id', sa.String(length=80), nullable=False),
    sa.Column('employee_id', sa.String(length=80), nullable=False),
    sa.Column('service_id', sa.String(length=80), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('planned_end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('real_end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['institute_id'], ['institutes.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['ticket_line_id'], ['ticket_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_sessions_employee_id'), 'service_sessions', ['employee_id'], unique=False)
    op.create_index(op.f('ix_service_sessions_institute_id'), 'service_sessions', ['institute_id'], unique=False)
    op.create_index(op.f('ix_service_sessions_status'), 'service_sessions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_sessions_status'), table_name='service_sessions')
    op.drop_index(op.f('ix_service_sessions_institute_id'), table_name='service_sessions')
    op.drop_index(op.f('ix_service_sessions_employee_id'), table_name='service_sessions')
    op.drop_table('service_sessions')
    op.drop_index(op.f('ix_ticket_lines_ticket_id'), table_name='ticket_lines')
    op.drop_table('ticket_lines')
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_start_time'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_service_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_institute_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_end_time'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_employee_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_queue_tickets_ticket_number'), table_name='queue_tickets')
    op.drop_index(op.f('ix_queue_tickets_status'), table_name='queue_tickets')
    op.drop_index(op.f('ix_queue_tickets_institute_id'), table_name='queue_tickets')
    op.drop_index(op.f('ix_queue_tickets_idempotency_key'), table_name='queue_tickets')
    op.drop_table('queue_tickets')
    op.drop_index(op.f('ix_employees_institute_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_table('institutes')
    op.drop_table('regions')
    op.drop_index(op.f('ix_services_category_id'), table_name='services')
    op.drop_table('services')
    op.drop_table('countries')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('service_categories')
    op.drop_table('companies')
    # ### end Alembic commands ###
